export const SET_TEMPLATE_LIST = 'SET_TEMPLATE_LIST';
export const SET_TEMPLATE_PREVIEW = 'SET_TEMPLATE_PREVIEW';
export const SET_CONTRACT_LIST = 'SET_CONTRACT_LIST';
export const SET_CONTRACT_PREVIEW = 'SET_CONTRACT_PREVIEW';

export const SET_TEMPLATE_CATEGORIES = 'SET_TEMPLATE_CATEGORIES';

export const SET_NEW_TEMPLATE = 'SET_NEW_TEMPLATE';
export const SET_DEFAULT_TEMPLATE = 'SET_DEFAULT_TEMPLATE';
export const SET_CLAUSES = 'SET_CLAUSES';

export const TOGGLE_DIALOG = 'TOGGLE_DIALOG';

export const CLEAR_STORE = 'CLEAR_STORE';

export const COPY_TEMPLATE = 'COPY_TEMPLATE';
